import { MetricFormData } from '@/lib/validations/challenge';

export interface ChallengeTemplate {
  id: string;
  name: string;
  description: string;
  category: 'fitness' | 'productivity' | 'learning' | 'wellness';
  icon: string;
  metrics: Omit<MetricFormData, 'id' | 'order'>[];
  settings: {
    enable_streak_bonus: boolean;
    streak_bonus_points: number;
    enable_perfect_day_bonus: boolean;
    perfect_day_bonus_points: number;
    lock_entries_after_day: boolean;
  };
}

export const challengeTemplates: ChallengeTemplate[] = [
  {
    id: 'fitness-challenge',
    name: 'Fitness Challenge',
    description: 'Track your daily workouts, steps, and hydration',
    category: 'fitness',
    icon: 'Dumbbell',
    metrics: [
      {
        name: 'Workout Duration',
        type: 'duration',
        required: true,
        config: { min: 0, max: 300 },
        points: 10,
        scoring_mode: 'scaled',
        threshold: 30,
        threshold_type: 'min',
      },
      {
        name: 'Steps Walked',
        type: 'number',
        required: true,
        config: { min: 0, max: 50000, units: 'steps' },
        points: 10,
        scoring_mode: 'scaled',
        threshold: 8000,
        threshold_type: 'min',
      },
      {
        name: 'Water Intake',
        type: 'number',
        required: true,
        config: { min: 0, max: 20, units: 'glasses' },
        points: 5,
        scoring_mode: 'scaled',
        threshold: 8,
        threshold_type: 'min',
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 5,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 10,
      lock_entries_after_day: false,
    },
  },
  {
    id: 'healthy-habits',
    name: 'Healthy Habits',
    description: 'Build a foundation of exercise, nutrition, sleep, and mindfulness',
    category: 'wellness',
    icon: 'Heart',
    metrics: [
      {
        name: 'Exercise Completed',
        type: 'boolean',
        required: true,
        config: {},
        points: 10,
      },
      {
        name: 'Healthy Eating',
        type: 'boolean',
        required: true,
        config: {},
        points: 10,
      },
      {
        name: 'Sleep Hours',
        type: 'number',
        required: true,
        config: { min: 0, max: 12, units: 'hours' },
        points: 10,
        scoring_mode: 'scaled',
        threshold: 7,
        threshold_type: 'min',
      },
      {
        name: 'Meditation',
        type: 'boolean',
        required: false,
        config: {},
        points: 5,
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 5,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 15,
      lock_entries_after_day: false,
    },
  },
  {
    id: 'productivity-master',
    name: 'Productivity Master',
    description: 'Optimize your focus, task completion, and daily planning',
    category: 'productivity',
    icon: 'Target',
    metrics: [
      {
        name: 'Deep Work Sessions',
        type: 'duration',
        required: true,
        config: { min: 0, max: 480 },
        points: 15,
        scoring_mode: 'scaled',
        threshold: 120,
        threshold_type: 'min',
      },
      {
        name: 'Task Completion Rate',
        type: 'number',
        required: true,
        config: { min: 0, max: 100, units: '%' },
        points: 15,
        scoring_mode: 'scaled',
        threshold: 80,
        threshold_type: 'min',
      },
      {
        name: 'Distraction-Free Hours',
        type: 'duration',
        required: true,
        config: { min: 0, max: 480 },
        points: 10,
        scoring_mode: 'scaled',
        threshold: 60,
        threshold_type: 'min',
      },
      {
        name: 'Daily Planning Done',
        type: 'boolean',
        required: false,
        config: {},
        points: 5,
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 10,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 20,
      lock_entries_after_day: false,
    },
  },
  {
    id: 'morning-routine',
    name: 'Morning Routine',
    description: 'Start your day right with healthy morning habits',
    category: 'wellness',
    icon: 'Sunrise',
    metrics: [
      {
        name: 'Wake Up Time',
        type: 'choice',
        required: true,
        config: { options: ['Before 6am', '6-7am', '7-8am', 'After 8am'] },
        points: 10,
      },
      {
        name: 'Morning Exercise',
        type: 'boolean',
        required: true,
        config: {},
        points: 10,
      },
      {
        name: 'Healthy Breakfast',
        type: 'boolean',
        required: true,
        config: {},
        points: 5,
      },
      {
        name: 'Journaling',
        type: 'boolean',
        required: false,
        config: {},
        points: 5,
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 5,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 10,
      lock_entries_after_day: false,
    },
  },
  {
    id: 'study-challenge',
    name: 'Study Challenge',
    description: 'Dedicated study time with reflection and note-taking',
    category: 'learning',
    icon: 'GraduationCap',
    metrics: [
      {
        name: 'Study Time',
        type: 'duration',
        required: true,
        config: { min: 0, max: 480 },
        points: 20,
        scoring_mode: 'scaled',
        threshold: 120,
        threshold_type: 'min',
      },
      {
        name: 'What I Learned Today',
        type: 'text',
        required: false,
        config: { maxLength: 500, placeholder: 'Reflect on what you learned...' },
        points: 5,
      },
      {
        name: 'Notes Taken',
        type: 'boolean',
        required: true,
        config: {},
        points: 5,
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 10,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 15,
      lock_entries_after_day: false,
    },
  },
  {
    id: 'reading-challenge',
    name: 'Reading Challenge',
    description: 'Track your reading time, materials, and key insights',
    category: 'learning',
    icon: 'BookOpen',
    metrics: [
      {
        name: 'Reading Time',
        type: 'duration',
        required: true,
        config: { min: 0, max: 480 },
        points: 15,
        scoring_mode: 'scaled',
        threshold: 30,
        threshold_type: 'min',
      },
      {
        name: 'Book/Document Name',
        type: 'text',
        required: true,
        config: { maxLength: 200, placeholder: 'What are you reading?' },
        points: 5,
      },
      {
        name: 'Key Highlights',
        type: 'text',
        required: false,
        config: { maxLength: 500, placeholder: 'Important passages or insights...' },
        points: 10,
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 5,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 10,
      lock_entries_after_day: false,
    },
  },
  {
    id: 'mindfulness-gratitude',
    name: 'Mindfulness & Gratitude',
    description: 'Cultivate mindfulness, gratitude, and meaningful connections',
    category: 'wellness',
    icon: 'Sparkles',
    metrics: [
      {
        name: 'Meditation',
        type: 'duration',
        required: true,
        config: { min: 0, max: 120 },
        points: 10,
        scoring_mode: 'scaled',
        threshold: 10,
        threshold_type: 'min',
      },
      {
        name: 'Gratitude Practice',
        type: 'boolean',
        required: true,
        config: {},
        points: 10,
      },
      {
        name: 'Daily Insights Journal',
        type: 'text',
        required: false,
        config: { maxLength: 500, placeholder: 'Write about your insights and gratitude...' },
        points: 10,
      },
      {
        name: 'Acts of Kindness',
        type: 'number',
        required: false,
        config: { min: 0, max: 20, units: 'acts' },
        points: 5,
        scoring_mode: 'scaled',
        threshold: 1,
        threshold_type: 'min',
      },
      {
        name: 'Phone-Free Time',
        type: 'duration',
        required: false,
        config: { min: 0, max: 480 },
        points: 5,
        scoring_mode: 'scaled',
        threshold: 60,
        threshold_type: 'min',
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 5,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 15,
      lock_entries_after_day: false,
    },
  },
  {
    id: 'no-zero-days',
    name: 'No-Zero Days',
    description: 'Make progress every single day, no matter how small',
    category: 'productivity',
    icon: 'Zap',
    metrics: [
      {
        name: 'Any Progress Made',
        type: 'boolean',
        required: true,
        config: {},
        points: 20,
      },
      {
        name: 'What You Accomplished',
        type: 'text',
        required: true,
        config: { maxLength: 500, placeholder: 'Describe what you did today...' },
        points: 10,
      },
      {
        name: "Tomorrow's Commitment",
        type: 'text',
        required: true,
        config: { maxLength: 300, placeholder: 'What will you do tomorrow?' },
        points: 5,
      },
    ],
    settings: {
      enable_streak_bonus: true,
      streak_bonus_points: 10,
      enable_perfect_day_bonus: true,
      perfect_day_bonus_points: 20,
      lock_entries_after_day: false,
    },
  },
];

export const templateCategories = [
  { id: 'all', name: 'All Templates' },
  { id: 'fitness', name: 'Fitness' },
  { id: 'productivity', name: 'Productivity' },
  { id: 'learning', name: 'Learning' },
  { id: 'wellness', name: 'Wellness' },
] as const;
